"""Topic and transcription metadata independent from mutable learning progress."""

from collections import Counter
from typing import Mapping

from mydictionary.content import (
    entry_topics,
    meaning_text,
    target_text,
    transcription_text,
)

JA_ROMAJI = {
    "こんにちは": "konnichiwa",
    "おはよう": "ohayou",
    "こんばんは": "konbanwa",
    "さようなら": "sayounara",
    "ありがとう": "arigatou",
    "すみません": "sumimasen",
    "ごめんなさい": "gomennasai",
    "お願いします": "onegaishimasu",
    "はい": "hai",
    "いいえ": "iie",
    "私": "watashi",
    "あなた": "anata",
    "人": "hito",
    "友達": "tomodachi",
    "家族": "kazoku",
    "父": "chichi",
    "母": "haha",
    "兄": "ani",
    "姉": "ane",
    "子供": "kodomo",
    "名前": "namae",
    "先生": "sensei",
    "学生": "gakusei",
    "学校": "gakkou",
    "会社": "kaisha",
    "家": "ie",
    "部屋": "heya",
    "店": "mise",
    "駅": "eki",
    "国": "kuni",
    "日本": "nihon",
    "水": "mizu",
    "お茶": "ocha",
    "ご飯": "gohan",
    "パン": "pan",
    "肉": "niku",
    "魚": "sakana",
    "野菜": "yasai",
    "果物": "kudamono",
    "りんご": "ringo",
    "今日": "kyou",
    "明日": "ashita",
    "昨日": "kinou",
    "今": "ima",
    "朝": "asa",
    "昼": "hiru",
    "夜": "yoru",
    "時間": "jikan",
    "日": "hi",
    "週": "shuu",
    "月": "tsuki",
    "年": "toshi",
    "一": "ichi",
    "二": "ni",
    "三": "san",
    "四": "yon",
    "五": "go",
    "六": "roku",
    "七": "nana",
    "八": "hachi",
    "九": "kyuu",
    "十": "juu",
    "大きい": "ookii",
    "小さい": "chiisai",
    "新しい": "atarashii",
    "古い": "furui",
    "良い": "ii",
    "悪い": "warui",
    "高い": "takai",
    "安い": "yasui",
    "暑い": "atsui",
    "寒い": "samui",
    "忙しい": "isogashii",
    "楽しい": "tanoshii",
    "好き": "suki",
    "行く": "iku",
    "来る": "kuru",
    "見る": "miru",
    "聞く": "kiku",
    "話す": "hanasu",
    "読む": "yomu",
    "書く": "kaku",
    "食べる": "taberu",
    "飲む": "nomu",
    "買う": "kau",
    "使う": "tsukau",
    "分かる": "wakaru",
    "知る": "shiru",
    "ある": "aru",
    "いる": "iru",
    "する": "suru",
    "寝る": "neru",
    "起きる": "okiru",
    "働く": "hataraku",
    "勉強する": "benkyou suru",
    "ここ": "koko",
    "そこ": "soko",
    "どこ": "doko",
    "何": "nani",
    "どう": "dou",
}
JA_ROMAJI.update({
    "...になる": "ninaru",
    "…が好き": "ga suki",
    "…の方を好む": "no houwo konomu",
    "あそこ": "asoko",
    "ありうる": "ariuru",
    "いつも": "itsumo",
    "いとこ": "itoko",
    "おば": "oba",
    "お婆さん": "o baasan",
    "お父さん": "o tousan",
    "お爺さん": "o jiisan",
    "くつろぐ": "kutsurogu",
    "ここに": "kokoni",
    "じゃがいも": "jagaimo",
    "すぐに": "suguni",
    "その時": "sono toki",
    "とても": "totemo",
    "なくす": "nakusu",
    "について": "nitsuite",
    "まだ": "mada",
    "もう一度": "mou ichido",
    "もっといい": "mottoii",
    "よく": "yoku",
    "アイスクリーム": "aisukuriimu",
    "アパート": "apaato",
    "イベント": "ibento",
    "インタビュー": "intabyuu",
    "ウエーター": "ueetaa",
    "オレンジ": "orenji",
    "カード": "kaado",
    "クラス": "kurasu",
    "クラブ": "kurabu",
    "クリーム": "kuriimu",
    "ケーキ": "keeki",
    "コース": "koosu",
    "コート": "kooto",
    "サッカー": "sakkaa",
    "サラダ": "sarada",
    "サンドイッチ": "sandoitchi",
    "シャツ": "shatsu",
    "シャワー": "shawaa",
    "ショッピングモール": "shoppingumooru",
    "ジャケット": "jaketto",
    "ジーンズ": "jiinzu",
    "スカート": "sukaato",
    "スタイル": "sutairu",
    "スーパーマーケット": "suupaamaaketto",
    "ズボン": "zubon",
    "セーター": "seetaa",
    "タクシー": "takushii",
    "ダンサー": "dansaa",
    "チョコレート": "chokoreeto",
    "チーム": "chiimu",
    "ティーネージャー": "teiineejaa",
    "テスト": "tesuto",
    "テニス": "tenisu",
    "トマト": "tomato",
    "トラック": "torakku",
    "バスケットボール": "basukettobooru",
    "バール": "baaru",
    "パスポート": "pasupooto",
    "パーティー": "paateii",
    "パートナー": "paatonaa",
    "ピンク": "pinku",
    "ブログ": "burogu",
    "プレゼント": "purezento",
    "プール": "puuru",
    "ペンキ": "penki",
    "ポンド": "pondo",
    "マイル": "mairu",
    "メニュー": "menyuu",
    "メモ": "memo",
    "モダンな": "modan na",
    "モデル": "moderu",
    "レストラン": "resutoran",
    "ワンピース": "wanpiisu",
    "一度": "ichido",
    "一時間": "ichijikan",
    "中心": "chuushin",
    "主要な": "shuyou na",
    "乗る": "noru",
    "予定": "yotei",
    "事実": "jijitsu",
    "事業": "jigyou",
    "二度": "nido",
    "交通": "koutsuu",
    "人気のある": "ninki noaru",
    "今晩": "konban",
    "企業": "kigyou",
    "休暇": "kyuuka",
    "会う": "au",
    "会員": "kaiin",
    "会話": "kaiwa",
    "伝言": "dengon",
    "伯父": "oji",
    "伺う": "ukagau",
    "似ている": "nite iru",
    "住所": "juusho",
    "使える": "tsukae ru",
    "例": "rei",
    "価格": "kakaku",
    "便": "bin",
    "保持する": "hoji suru",
    "信じる": "shinji ru",
    "俳優": "haiyuu",
    "個人の": "kojin no",
    "健康": "kenkou",
    "偽": "nise",
    "優しい": "yasashii",
    "光": "hikari",
    "公演": "kouen",
    "写真": "shashin",
    "分配する": "bunpai suru",
    "切る": "kiru",
    "到着する": "touchaku suru",
    "前": "mae",
    "劇場": "gekijou",
    "加える": "kuwae ru",
    "助言": "jogen",
    "労働者": "roudousha",
    "動く": "ugoku",
    "動物": "doubutsu",
    "勝つ": "katsu",
    "十分に": "juubun ni",
    "半分": "hanbun",
    "南": "minami",
    "博物館": "hakubutsukan",
    "危険": "kiken",
    "同じ": "onaji",
    "同意する": "doui suru",
    "否定の": "hitei no",
    "含む": "fukumu",
    "唯一の": "yuiitsu no",
    "商品": "shouhin",
    "問題": "mondai",
    "喉が渇いた": "nodo ga katsu ita",
    "四分の一": "yonbun no ichi",
    "回転": "kaiten",
    "図表": "zuhyou",
    "土曜日": "doyoubi",
    "地図": "chizu",
    "地理学": "chirigaku",
    "報告": "houkoku",
    "声明": "seimei",
    "売る": "uru",
    "変える": "kae ru",
    "夕食": "yuushoku",
    "外に": "soto ni",
    "多分": "tabun",
    "夜中": "yonaka",
    "大学": "daigaku",
    "天気": "tenki",
    "女優": "joyuu",
    "妻": "tsuma",
    "始める": "hajime ru",
    "学ぶ": "manabu",
    "学習": "gakushuu",
    "安価": "anka",
    "完全な": "kanzen na",
    "客": "kyaku",
    "宿題": "shukudai",
    "寝室": "shinshitsu",
    "対談": "taidan",
    "山": "yama",
    "年齢": "nenrei",
    "床": "toko",
    "庭": "niwa",
    "建てる": "tate ru",
    "建物": "tatemono",
    "強い": "tsuyoi",
    "形状": "keijou",
    "彼女": "kanojo",
    "彼氏": "kareshi",
    "待つ": "matsu",
    "後に": "nochini",
    "得る": "eru",
    "復帰": "fukki",
    "忘れる": "wasure ru",
    "怒った": "ikatsu ta",
    "怖い": "kowai",
    "思い出す": "omoidasu",
    "恋しく思う": "koishiku omou",
    "恐ろしい": "osoroshii",
    "情報": "jouhou",
    "想像する": "souzou suru",
    "意味する": "imi suru",
    "意義": "igi",
    "意見": "iken",
    "愛しい": "itoshii",
    "感じのよい": "kanji noyoi",
    "感じる": "kanji ru",
    "感覚": "kankaku",
    "感謝する": "kanshasu ru",
    "憎む": "nikumu",
    "成人": "seijin",
    "成功": "seikou",
    "成長する": "seichousu ru",
    "技能": "ginou",
    "持って来る": "motsu te kuru",
    "挑戦する": "chousen suru",
    "授業": "jugyou",
    "描く": "egaku",
    "改良する": "kairyou suru",
    "敏い": "satoi",
    "教える": "oshie ru",
    "教室": "kyoushitsu",
    "散歩": "sanpo",
    "文": "bun",
    "料理": "ryouri",
    "新聞": "shinbun",
    "旅行": "ryokou",
    "旅行する": "ryokou suru",
    "旅行者": "ryokousha",
    "日曜日": "nichiyoubi",
    "早い": "hayai",
    "明確な": "meikaku na",
    "昼食": "chuushoku",
    "時時": "tokidoki",
    "最高の": "saikou no",
    "月曜日": "getsuyoubi",
    "有名": "yuumei",
    "朝食": "choushoku",
    "期間": "kikan",
    "木曜日": "mokuyoubi",
    "未来": "mirai",
    "本文": "honbun",
    "机": "tsukue",
    "植物": "shokubutsu",
    "楽しみ": "tanoshimi",
    "楽しむ": "tanoshi mu",
    "樹液": "jueki",
    "機械": "kikai",
    "次の": "tsugino",
    "歌う": "utau",
    "歌手": "kashu",
    "正しい": "tadashii",
    "正確": "seikaku",
    "死ぬ": "shinu",
    "残す": "nokosu",
    "段落": "danraku",
    "比べる": "kurabe ru",
    "水曜日": "suiyoubi",
    "水泳": "suiei",
    "氷": "koori",
    "汁": "shiru",
    "汚い": "kitanai",
    "決して": "kesshite",
    "注文": "chuumon",
    "活動": "katsudou",
    "浜": "hama",
    "涼しい": "suzushii",
    "湯船": "yubune",
    "満たす": "mita su",
    "準備する": "junbi suru",
    "火曜日": "kayoubi",
    "灰色": "haiiro",
    "点": "ten",
    "物体": "buttai",
    "特別な": "tokubetsu na",
    "現地": "genchi",
    "現実の": "genjitsu no",
    "理由": "riyuu",
    "理解する": "rikai suru",
    "生み出す": "umidasu",
    "用いる": "mochii ru",
    "留まる": "tomaru",
    "異なる": "kotonaru",
    "登る": "noboru",
    "相互": "sougo",
    "看護師": "kango shi",
    "真実の": "shinjitsu no",
    "着る": "kiru",
    "瞬間": "shunkan",
    "知らせ": "shirase",
    "砂糖": "satou",
    "硬い": "katai",
    "確か": "tashika",
    "確信している": "kakushin shiteiru",
    "祭り": "matsuri",
    "科学者": "kagakusha",
    "科目": "kamoku",
    "称号": "shougou",
    "空気": "kuuki",
    "空腹な": "kuufuku na",
    "空間": "kuukan",
    "競技場": "kyougijou",
    "筆記": "hikki",
    "簡単な": "kantan na",
    "紙": "kami",
    "素晴しい": "subarashii",
    "素晴らしい": "subarashii",
    "紫色": "murasakiiro",
    "紹介する": "shoukai suru",
    "終了": "shuuryou",
    "終了する": "shuuryou suru",
    "経歴": "keireki",
    "結婚している": "kekkon shiteiru",
    "結果": "kekka",
    "絵": "e",
    "絵画": "kaiga",
    "綴り": "tsuzuri",
    "綴る": "tsuzuru",
    "綺麗な": "kirei na",
    "緑の": "midori no",
    "練習": "renshuu",
    "繁華": "hanka",
    "繋げる": "tsunage ru",
    "繰り返す": "kurikaesu",
    "置く": "oku",
    "美しい": "utsukushii",
    "美味しい": "oishii",
    "耳": "mimi",
    "胡椒": "koshou",
    "腕": "ude",
    "腕時計": "udedokei",
    "自然な": "shizen na",
    "自由": "jiyuu",
    "自身の": "jishin no",
    "自転車": "jitensha",
    "興味": "kyoumi",
    "興奮する": "koufun suru",
    "芸術家": "geijutsuka",
    "若い": "wakai",
    "茶色い": "chairoi",
    "著者": "chosha",
    "行う": "okonau",
    "行動": "koudou",
    "衣服": "ifuku",
    "見付ける": "mitsuke ru",
    "規則": "kisoku",
    "親切な": "shinsetsu na",
    "解決する": "kaiketsu suru",
    "言う": "iu",
    "計画": "keikaku",
    "記事": "kiji",
    "記述": "kijutsu",
    "記述する": "kijutsu suru",
    "訪問する": "houmon suru",
    "訪問者": "houmonsha",
    "設計": "sekkei",
    "許す": "yurusu",
    "詳細": "shousai",
    "誕生日": "tanjoubi",
    "説明する": "setsumeisu ru",
    "読書": "dokusho",
    "読者": "dokusha",
    "調べる": "shirabe ru",
    "調理": "chouri",
    "警察": "keisatsu",
    "議論する": "giron suru",
    "貧しい": "mazushii",
    "買い物": "kaimono",
    "費用": "hiyou",
    "購入する": "kounyuu suru",
    "起こる": "oko ru",
    "農場": "noujou",
    "農夫": "noufu",
    "近い": "chikai",
    "追う": "ou",
    "退屈した": "taikutsu shita",
    "送る": "okuru",
    "通常": "tsuujou",
    "速い": "hayai",
    "週末": "shuumatsu",
    "遅い": "osoi",
    "運動": "undou",
    "運転する": "unten suru",
    "運転手": "untenshu",
    "過去": "kako",
    "違い": "chigai",
    "遠く": "tooku",
    "選ぶ": "erabu",
    "選手": "senshu",
    "重要": "juuyou",
    "野球": "yakyuu",
    "金曜日": "kinyoubi",
    "金髪の": "kinpatsu no",
    "鉛筆": "enpitsu",
    "長い": "nagai",
    "閉める": "shime ru",
    "開始": "kaishi",
    "開始する": "kaishi suru",
    "間違った": "machigatsu ta",
    "隣": "tonari",
    "集団": "shuudan",
    "雑誌": "zasshi",
    "難しい": "muzukashii",
    "電子メール": "denshimeeru",
    "電話": "denwa",
    "青物": "aomono",
    "静かな": "shizuka na",
    "面白い": "omoshiroi",
    "面積": "menseki",
    "靴": "kutsu",
    "飛行機": "hikouki",
    "食事": "shokuji",
    "首都": "shuto",
    "馬": "uma",
    "驚くべき": "odoroku beki",
    "黄色い": "kiiroi",
})


def _terms(value: str) -> frozenset[str]:
    return frozenset(value.split("|"))


LANG_TOPIC_TERMS = {
    "ja": {
        "greetings": _terms(
            "こんにちは|おはよう|こんばんは|さようなら|ありがとう|すみません|"
            "ごめんなさい|お願いします|はい|いいえ"
        ),
        "communication": _terms(
            "名前|見る|聞く|話す|読む|書く|分かる|知る|何|どう|お願いします"
        ),
        "people": _terms(
            "私|あなた|人|友達|家族|父|母|兄|姉|子供|名前|先生|学生"
        ),
        "food": _terms(
            "水|お茶|ご飯|パン|肉|魚|野菜|果物|りんご|食べる|飲む|買う"
        ),
        "home": _terms("家|部屋|店|ある|いる|ここ|そこ"),
        "travel": _terms("駅|国|日本|行く|来る|ここ|そこ|どこ"),
        "time": _terms(
            "今日|明日|昨日|今|朝|昼|夜|時間|日|週|月|年|一|二|三|四|五|六|七|八|九|十"
        ),
        "work": _terms("先生|学生|学校|会社|忙しい|読む|書く|働く|勉強する"),
        "actions": _terms(
            "行く|来る|見る|聞く|話す|読む|書く|食べる|飲む|買う|使う|分かる|"
            "知る|ある|いる|する|寝る|起きる|働く|勉強する"
        ),
        "descriptions": _terms(
            "大きい|小さい|新しい|古い|良い|悪い|高い|安い|暑い|寒い|忙しい|楽しい|好き"
        ),
    },
    "vi": {
        "greetings": _terms("xin chào|tạm biệt|cảm ơn|xin lỗi|vâng|không"),
        "communication": _terms(
            "biết|hiểu|nói|nghe|đọc|viết|bao nhiêu|ở đâu|khi nào|tại sao|gì|ai|thế nào"
        ),
        "people": _terms("tôi|bạn|anh|chị|chúng tôi|họ|người|bạn bè|gia đình|con"),
        "food": _terms("ăn|uống|nước|cơm|phở|cà phê|ngon|nhà hàng|đói|khát"),
        "home": _terms("nhà|chợ|đường"),
        "travel": _terms("đi|đến|về|đường|xe|máy bay|khách sạn|nhà hàng|bệnh viện|ở đâu"),
        "time": _terms(
            "một|hai|ba|bốn|năm|mười|bao nhiêu|khi nào|hôm nay|ngày mai|hôm qua|"
            "bây giờ|giờ|ngày|tuần|tháng"
        ),
        "work": _terms("làm|học|dạy|trường|tiền|bán|mua"),
        "actions": _terms(
            "muốn|cần|biết|hiểu|nói|nghe|đọc|viết|ăn|uống|đi|đến|về|làm|mua|bán|"
            "thích|yêu|sống|học|dạy|cho|lấy|tìm|đợi|giúp"
        ),
        "descriptions": _terms(
            "tốt|xấu|đẹp|lớn|nhỏ|mới|cũ|nóng|lạnh|ngon|đắt|trẻ|nhanh|chậm|nhiều|"
            "ít|đẹp trai|vui|buồn|mệt|đói|khát"
        ),
    },
}


EN_TOPIC_KEYWORDS = {
    "communication": (
        "cover the topic", "twang", "glance", "define", "remind", "yell", "babble",
        "request", "claim", "rumor", "eloquent", "complain", "confess", "summarize",
        "respond", "utter", "reveal", "arguing", "poll", "plead", "proofread",
    ),
    "people": (
        "fraternity", "intern", "execs", "governor", "martyr", "relative", "darling",
        "crusader", "guard", "judge", "monk", "mentor", "bride", "coward", "participants",
    ),
    "food": (
        "candy", "nutritious", "shrimp", "buns", "nutrients", "gluten", "herbal",
        "garlic", "taste", "canteen", "cereal", "pilsner", "brew", "partake",
    ),
    "home": (
        "mug", "laundry", "faucet", "napkin", "envelope", "mansion", "ceiling", "tape",
        "glue", "strap", "leash", "lodge", "outfit", "lighters",
    ),
    "travel": (
        "entry", "vehicle", "van", "yacht", "reservation", "route", "cycle parking",
        "on-site", "field", "fire station", "asylums", "pitches",
    ),
    "time": (
        "ninth", "thirties", "schedule", "still", "expected", "noon", "current",
        "elapsed", "immediately", "currently", "recently", "ever", "lasting",
    ),
    "work": (
        "effort", "activity", "intern", "schedule", "requirements", "responsibilities",
        "lesson", "opportunity", "assignment", "mentor", "taught", "literacy", "conducted",
        "proofread", "available", "output", "parameters",
    ),
    "business": (
        "consumption", "exchange", "distribution", "revenue", "execs", "promote",
        "bargain", "solvency", "inflation", "distributers", "takeover", "acquisitions",
        "insurance", "purchase", "welfare", "accountancy", "trade-off", "concession",
        "benefits", "negotiation", "debt", "acquiring", "gross", "venture", "merger",
        "offer", "afford", "underwrite", "undersell", "underpay", "current account surplus",
    ),
    "health": (
        "pneumonia", "morgue", "cure", "inhale", "injured", "sweating", "tissue",
        "aid kit", "nerve", "cell", "anxiety", "medulla", "diazepam", "inoculation",
        "tinnitus", "fever", "spleen", "consciousness", "addiction", "craving",
    ),
    "nature": (
        "contaminate", "isosceles", "bushfire", "habitat", "environment", "drought",
        "surface", "rectangles", "globes", "fiber", "particle", "silt", "cesium",
        "scale", "projection", "flow", "strand", "velocity", "density", "oak", "sow",
    ),
    "technology": (
        "conduit", "cutting edge", "backup", "amp", "compilation", "parameters", "slider",
        "script", "output", "cipher", "barcode", "gears", "release", "reboot", "disable",
    ),
    "actions": (
        "carry on", "serve", "yield", "gather", "kidnap", "adopt", "forgive", "promote",
        "extend", "conform", "govern", "remind", "throw", "beg", "wind up", "haul",
        "figure out", "feed", "behave", "bury", "soothe", "dig", "borrow", "deal with",
        "accuse", "chase", "smash", "engrave", "step aside", "reject", "follow up",
        "introduce", "let off", "resist", "engage", "stay out", "reduce", "undo",
        "retire", "break down", "allow", "avoid", "catch up", "get off", "wipe out",
        "keep", "prevent", "solve", "undertake", "strive", "retrace",
    ),
    "descriptions": (
        "oddity", "vanity", "superior", "weary", "stubborn", "tense", "unreliable",
        "idle", "disingenuous", "embarrassed", "furious", "curious", "particular",
        "worthless", "wan", "thick", "thin", "stale", "unjust", "miserable", "vague",
        "harsh", "grateful", "sturdy", "jealous", "hilarious", "fragile", "deceitful",
        "gentle", "neutral", "significant", "irresistible", "impatient", "quirky",
        "innocent", "suspicious", "decent", "humble", "smooth", "strict", "bizarre",
        "sensitive", "attractive", "arrogant", "brash", "desperate", "restless",
        "precious", "adorable", "sober", "tough", "grouchy", "livid",
    ),
}


def transcription_for(word: dict, lang: str) -> str:
    """Return a learner-friendly pronunciation or transliteration."""
    canonical = transcription_text(word)
    if canonical:
        return canonical
    if lang == "ja":
        return JA_ROMAJI.get(target_text(word), "")
    return ""


def topics_for_word(word: dict, lang: str) -> tuple[str, ...]:
    """Return one or more stable topic ids for a dictionary entry."""
    canonical = entry_topics(word)
    if canonical:
        return canonical
    term = target_text(word)
    topics = []

    for topic, terms in LANG_TOPIC_TERMS.get(lang, {}).items():
        if term in terms:
            topics.append(topic)

    if lang == "en":
        haystack = " ".join((term, meaning_text(word))).lower()
        for topic, keywords in EN_TOPIC_KEYWORDS.items():
            if any(keyword in haystack for keyword in keywords):
                topics.append(topic)

    if not topics:
        topics.append("general")

    return tuple(dict.fromkeys(topics))


def topic_counts(
    words: list[dict],
    lang: str,
    *,
    topic_labels: Mapping[str, str],
) -> dict[str, int]:
    """Count entries for each topic in display order."""
    counts = Counter(
        topic
        for word in words
        for topic in topics_for_word(word, lang)
    )
    return {
        topic: counts[topic]
        for topic in topic_labels
        if counts[topic]
    }
